# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ef33f8d108efa2a2359da03a26da98581a0bcba11b16dbbf0af2b27d355e5e97d461b6ba4ba97fa9f0ee2fd977c9979e925e34f96f33c5a98d470c9c1f83c72

test:
  secret_key_base: 2eb06d675c928d6ae374cd7900d7dbeddd33526a3255474853c0b34e80b57d3bf8a5e98730016286ff5e6bd9b7ffe562045716732399605b797620ab94848b05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
